global:
  scrape_interval: 15s
  
scrape_configs:
- job_name: node
  static_configs:
  - targets: ['172.17.0.1:9100','HAWK:9100'] #172.. should be ip of docker0 nic - config hawk and other clients in /etc/hosts
- job_name: prometheus_metrics
  static_configs:
  - targets: ['localhost:9090']
